version: '3.1'
services:
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        ports:
            - 80:80
        volumes:
           - ./frontend/index.html:/frontend/index.html
           - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - flask
        networks:
            - mapnetwork
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask:0.0.1
        container_name: flask
        volumes:
            - ./backend/main.py:/backend/main.py
            - ./backend/points.json:/backend/points.json
        environment:
            - FLASK_APP=/backend/main.py
        command: flask run --host=0.0.0.0
        ports:
            - 5000:5000
        networks:
            - mapnetwork
networks:
    mapnetwork:
        driver: bridge